services:
  client:
    build:
      context: client
      dockerfile: dockerfile
    command: ["yarn", "dev"]
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    depends_on:
      - api
  api:
    build:
      context: api
      dockerfile: dockerfile
    command: ["yarn", "dev"]
    volumes:
      - ./api:/app
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    build:
      context: db
      dockerfile: dockerfile
    volumes:
      - ./data:/app/data # 永続化
      - ./db/migration/result/:/app/migration/
    tty: true
  db-migration:
    build:
      context: db/migration
      dockerfile: dockerfile
    volumes:
      - ./db/migration:/app
      - node_modules:/app/node_modules
    working_dir: /app
    environment:
      DB_FILE_PATH: "./data/main.sqlite3"
    command: ["cp", "./data/main.sqlite3", "./db/migration/result"]
    tty: true
    depends_on:
      - db

volumes:
  node_modules: # 外部リソースとして非同期化
